services:
  obsidian-vps-publish:
    build:
      context: .
      dockerfile: Dockerfile

    image: obsidian-vps-publish:dev

    env_file:
      - .env.dev

    # environment:
    #   NODE_ENV: 'development'
    #   LOGGER_LEVEL: 'debug'
    #   ALLOWED_ORIGINS: '*,app://obsidian'
    #   AUTHOR: 'Jonathan Rouquette'
    #   REPO_URL: 'https://github.com/JoRouquette/obsidian-vps-publish'
